
module.exports = {
    "VALIDATE_REQUIRED": "This field is required",
    "VALIDATE_REMOTE": "Please fix this field",
    "VALIDATE_EMAIL": "Please enter a valid email address",
    "VALIDATE_EMAIL_UNIQUE": "This email is already registered",
    "VALIDATE_URL": "Please enter a valid URL",
    "VALIDATE_DATE": "Please enter a valid date",
    "VALIDATE_DATE_ISO": "Please enter a valid date ( ISO )",
    "VALIDATE_NUMBER": "Please enter a valid number",
    "VALIDATE_DIGITS": "Please enter only digits",
    "VALIDATE_CREDIT_CARD": "Please enter a valid credit card number",
    "VALIDATE_EQUAL_TO": "Please enter the same value again",
    "VALIDATE_MAX_LENGTH": "Please enter no more than {0} characters",
    "VALIDATE_MIN_LENGTH": "Please enter at least {0} characters",
    "VALIDATE_RANGE_LENGTH": "Please enter a value between {0} and {1} characters long",
    "VALIDATE_RANGE": "Please enter a value between {0} and {1}",
    "VALIDATE_MAX": "Please enter a value less than or equal to {0}",
    "VALIDATE_MIN": "Please enter a value greater than or equal to {0}",
    "VALIDATE_DAY_ERROR": "Enter Day",
    "VALIDATE_MONTH_ERROR": "Enter Month",
    "VALIDATE_YEAR_ERROR": "Enter Year",
    "BML_VALUE_ERROR": "Please Enter Valid Data",
    "BML_SSN": "Last 4 digits of your SSN",
    "BML_SSN_ERROR": "Enter last four digits of your SSN.",
    "BML_SSN_INVALID": "Your entry is invalid.",
    "BML_TERMS": "I have read and agree to the terms above",
    "BML_TERMS_ERROR": "You must agree to the terms and conditions",
    "PROFILE_FIRSTNAME": "First Name",
    "PROFILE_LASTNAME": "Last Name",
    "PROFILE_EMAIL": "Email",
    "PROFILE_CONFIRMEMAIL": "Confirm Email",
    "PROFILE_DOB": "Date of Birth",
    "PROFILE_BIRTHDAY": "Birthday",
    "PROFILE_DOB_EXAMPLE": "Example: 03/28/1968",
    "PROFILE_PHONE": "Phone",
    "PROFILE_PHONE_PLACEHOLDER": "123-456-7890",
    "PROFILE_PHONE_EXAMPLE": "Please use this format: 123-456-7890",
    "PROFILE_SUBSCRIBE_EMAIL_PLACEHOLDER": "Your email, please",
    "PROFILE_USERNAME_TAKEN": "Username already taken.",
    "PROFILE_PASSWORD_CONFIRM": "Confirm Password",
    "PROFILE_NEW_PASSWORD_CONFIRM": "Confirm New Password",
    "PROFILE_PASSWORD_NO_MATCH": "Does not match password",
    "PROFILE_CURRENTPASSWORDNOMATCH": "Does not match the current password",
    "PROFILE_NEWPASSWORD": "New Password",
    "PROFILE_ACCOUNT_QUESTION": "Security Question",
    "PROFILE_QUESTION1": "Mother's Maiden Name",
    "PROFILE_QUESTION2": "Make of First Car",
    "PROFILE_QUESTION3": "Favourite Pet's Name",
    "PROFILE_QUESTION4": "Father's First Name",
    "PROFILE_QUESTION5": "Place of Birth",
    "PROFILE_ACCOUNTANSWER": "Security Answer",
    "PROFILE_ADDEMAILTOLIST": "Join the mailing list to be first to know  about sales,event & new arrivals",
    "PROFILE_REMEMBER": "Remember Me",
    "PROFILE_USERNAMEERROR": "Username must be between 5 and 100 characters, and may only contain letters, numbers, spaces, periods, dashes, underscores, and @.",
    "ADDRESS_INVALID": "Some information below is either incomplete or needs to be corrected",
    "ADDRESS_FIELD_INVALID": "Please enter a valid value",
    "ADDRESS_FIRSTNAME_MISSING": "Please enter a First name",
    "ADDRESS_LASTNAME_MISSING": "Please enter a Last name",
    "ADDRESS_COUNTRY_MISSING": "Please select a Country",
    "ADDRESS_STATE_MISSING": "Please select a State",
    "ADDRESS_CITY_MISSING": "Please enter a City",
    "ADDRESS_PHONE_MISSING": "Please enter a Telephone Number",
    "ADDRESS_PHONE_EXAMPLE": "Example: 3334444555",
    "ADDRESS_EMAIL_INVALID": "Please enter a valid Email Address",
    "ADDRESS_POSTALCODE_EXAMPLE": "Example : 12345 or 12345-1234",
    "GIFTREGISTRY_EVENTTYPE_MISSING_ERROR": "Please select an event type.",
    "GIFTREGISTRY_EVENTNAME": "Event Name",
    "GIFTREGISTRY_EVENTNAME_MISSING_ERROR": "Please enter a name for this event.",
    "GIFTREGISTRY_EVENTDATE": "Event Date",
    "GIFTREGISTRY_EVENTDATE_DESCRIPTION": "Example: yyyy-MM-dd",
    "GIFTREGISTRY_EVENTDATE_MISSING_ERROR": "Please enter the event date in the format yyyy-MM-dd.",
    "GIFTREGISTRY_EVENTDATE_PARSE_ERROR": "Please enter a valid event date in the format yyyy-MM-dd.",
    "GIFTREGISTRY_EVENTCITY": "Event City",
    "GIFTREGISTRY_EVENTCITY_MISSING_ERROR": "Please enter the event city.",
    "GIFTREGISTRY_EVENTSTATE": "Event State",
    "GIFTREGISTRY_EVENT_COUNTRY": "Event Country",
    "GIFTREGISTRY_REGISTRANT_ROLE": "Role",
    "GIFTREGISTRY_REGISTRANT_ROLE_MISSING_ERROR": "Please select a role.",
    "GIFTREGISTRY_REGISTRANT_FIRSTNAME": "First Name",
    "GIFTREGISTRY_REGISTRANT_FIRSTNAME_MISSING_ERROR": "Please enter the first name of the registrant.",
    "GIFTREGISTRY_REGISTRANT_FIRSTNAME_PARSE_ERROR": "Please enter a valid first name.",
    "GIFTREGISTRY_REGISTRANT_LASTNAME": "Last Name",
    "GIFTREGISTRY_REGISTRANT_LASTNAME_MISSING_ERROR": "Please enter the last name of the registrant.",
    "GIFTREGISTRY_REGISTRANT_LASTNAME_PARSE_ERROR": "Please enter a valid last name.",
    "GIFTREGISTRY_REGISTRANT_EMAIL_MISSING_ERROR": "Please enter the registrant's email address.",
    "GIFTREGISTRY_REGISTRANT_EMAIL_PARSE_ERROR": "Please enter a valid email address.",
    "GIFTREGISTRY_ADDRESS_SOURCE_ADDRESS_BOOK": "Use address from Address Book",
    "GIFTREGISTRY_ADDRESS_SOURCE_NEW": "Create new address",
    "GIFTREGISTRY_ADDRESS_SOURCE_ASBEFORE": "Same address as before event",
    "GIFTREGISTRY_ITEMS_QUANTITY": "Quantity Desired",
    "GIFTREGISTRY_ITEMS_QUANTITY_MISSING_ERROR": "Please enter a quantity.",
    "GIFTREGISTRY_ITEMS_QUANTITY_PARSE_ERROR": "Please enter a valid quantity.",
    "GIFTREGISTRY_ITEMS_QUANTITY_VALUE_ERROR": "Please enter a valid quantity",
    "GIFTREGISTRY_ITEMS_PRIORITY": "Priority",
    "GIFTREGISTRY_ITEMS_PRIORITY_MISSING_ERROR": "Please enter a priority.",
    "GIFTREGISTRY_ITEMS_UPDATE": "Update",
    "GIFTREGISTRY_ITEMS_MAKEPUBLIC": "Make This Item Public",
    "GIFTREGISTRY_ITEMS_REMOVE": "Remove",
    "GIFTREGISTRY_SEND_LABEL": "Send to email addresses",
    "GIFTREGISTRY_SEND_CHECK": "Check your email address in Your Account - Personal Information.",
    "GIFTREGISTRY_SEND_INVALID": "Please enter valid email addresses.",
    "GIFTREGISTRY_SEND_FORMAT": "Please enter valid E-Mail addresses (separated by ', ' or '; ').",
    "GIFTREGISTRY_ADD_TO_ADDRESS_BOOK": "Add to Address Book",
    "GIFTREGISTRY_COPY_ADDRESS": "Use this address for Post Event Shipping",
    "WISHLIST_LNAME": "Last Name",
    "WISHLIST_FNAME": "First Name",
    "WISHLIST_SENDTO_EMAIL": "Send to email addresses",
    "WISHLIST_CHECK_EMAILADDRESS": "Check your email address in Your Account - Personal Information.",
    "WISHLIST_ENTER_VALIDEMAIL": "Please enter valid email addresses.",
    "WISHLIST_TITLE": "Title",
    "WISHLIST_PRICE_LTH": "Price (low to high)",
    "WISHLIST_PRICE_HTL": "Price (high to low)",
    "WISHLIST_DATEADDED": "Date Added",
    "WISHLIST_LASTUPDATED": "Last Updated",
    "WISHLIST_SORTBY": "Sort By",
    "WISHLIST_VALIDEMAIL": "Please enter valid E-Mail addresses (separated by ', ' or '; ').",
    "WISHLIST_SEARCH_LASTNAMEREQIURED": "You must supply a last name.",
    "WISHLIST_QUANTITYDESIRED": "Quantity Desired",
    "BILLING_COUPON_COUPONENTER": "Enter coupon code",
    "BILLING_COUPON_COUPONINVALID": "Invalid Coupon Code",
    "BILLING_COUPON_COUPONUSED": "This Promo Code has already been used",
    "BILLING_COUPON_COUPONEXPIRED": "Expired Promo Code",
    "BILLING_COUPON_COUPONALREADYAPPLIED": "The Coupon is already applied",
    "BILLING_COUPON_COUPONNOTQUALIFIED": "You have not qualified for the discount",
    "BILLING_GIFTCERT_GIFTCERT_LABEL ": "Redeem Gift Certificate",
    "BILLING_GIFTCERT_GIFTCARD_LABEL ": "Gift Card",
    "BILLING_GIFTCERT_GIFTCERT_INVALID ": "Invalid Gift Certificate",
    "BILLING_GIFTCERT_GIFTCERT_WRONG_CURRENCY ": "The gift Certificate can only be redeemed for orders placed in the same currency as the gift certificate",
    "BILLING_GIFTCERT_GIFTCERT_NOFUNDS ": "Insufficient Gift Certificate balance",
    "ACCOUNT_NOT_AUTHORIZED": "Not authorized"
}