module.exports = {
    "UPLOAD_IMAGE_SIZE_MAX": 950000,
    "UPLOAD_FILE_SIZE_MAX": 2097152,
    "REQUEST_STATUS_SUCCESS": 200,
    "REQUEST_STATUS_FAILED": 400,
    "REQUEST_MESSAGE_SUCCESS": "SUCCESS",
    "REQUEST_MESSAGE_FAILED": "FAILED",
}